### PR TITLE
Added additional sensors

### PR DESCRIPTION
**Pull request by 2000game**

### CODE REVIEW

**Comment by 2000game** [comment]
Depends on: https://github.com/CharlesGillanders/alphaess/pull/4

**Comment by Spookster** [comment]
Id like to assist with testing, but am struggling to get it installed following the standard instruction.
Ive added it via hacs / git so that the component exists:

image

The file structure exists (after removing the original alphaess files and restarting)

image

However Im failing on the next step with adding it as an integration (it doesnt exist) What is the simple step Im missing?

**Comment by Spookster** [comment]
Nice work so far, some comments:

You have 2 battery sensors:
AlphaESSSensor(coordinator,entry,serial,"Battery SOC", POWER_KILO_WATT),
AlphaESSSensor(coordinator,entry,serial,"State of Charge", PERCENTAGE),

The battery SOC as POWER_KILO_WATT only converts State of Charge from % to kW which is incorrect

**Comment by Spookster** [comment]
From Developer tools > Statistics:

image

**Comment by Spookster** [comment]
I see you also use ppv1 / ppv2 in your calculations, but dont use them as sensors?
Personally I find the values useful as sensors too, as it enables you to display the MPTT values for string 1 and 2 (thus the total solar generation)

**Comment by Spookster** [comment]
Yes, it can be very helpful with checking performance. Ive got 10 facing north and 5 facing east (due to space) and it gives enough visual information to justify the upgrade with a few more panels
The consumer interface doesnt split the the strings, so they can only be viewed via the installer interface.
So any and all information is quite handy at times.
Realistically for automation, I only use load/generation/battery values

image

**Comment by 2000game** [comment]
> Nice work so far, some comments:
> 
> You have 2 battery sensors: AlphaESSSensor(coordinator,entry,serial,"Battery SOC", POWER_KILO_WATT), AlphaESSSensor(coordinator,entry,serial,"State of Charge", PERCENTAGE),
> 
> The battery SOC as POWER_KILO_WATT only converts State of Charge from % to kW which is incorrect
> 
> < edit > I see the change above which wasnt pulled down into my code. So now there are just 2 sensors for the same SOC value

Ah my bad, I thought those were different values since State of Change is from statistical data and Battery SOC from powerdata which are different API endpoints in Alphaess

**Comment by 2000game** [comment]
> Yes, it can be very helpful with checking performance. Ive got 10 facing north and 5 facing east (due to space) and it gives enough visual information to justify the upgrade with a few more panels The consumer interface doesnt split the the strings, so they can only be viewed via the installer interface. So any and all information is quite handy at times. Realistically for automation, I only use load/generation/battery values
> 
> image

I don't know what all the values represent, since I'm only implementing the changes for a friend. But If you want I could add it to the PR, or @CharlesGillanders adds them himself.

**Comment by Spookster** [comment]
> > Nice work so far, some comments:
> > You have 2 battery sensors: AlphaESSSensor(coordinator,entry,serial,"Battery SOC", POWER_KILO_WATT), AlphaESSSensor(coordinator,entry,serial,"State of Charge", PERCENTAGE),
> > The battery SOC as POWER_KILO_WATT only converts State of Charge from % to kW which is incorrect
> > < edit > I see the change above which wasnt pulled down into my code. So now there are just 2 sensors for the same SOC value
> 
> Ah my bad, I thought those were different values since State of Change is from statistical data and Battery SOC from powerdata which are different API endpoints in Alphaess

Im not sure how that effects the end result as far as stats or power data. There may be an obscure reason why they are both required, but my skills dont extend to that level. From a monitoring perspective they seem to be the same value

**Pull request closed without merging**
