### PR TITLE
Force battery discharge and charge support & API Fixes

### PR DESCRIPTION
**Pull request by Poshy163**
- Update throttle to 1.4 (was 1.35) 
- Bump Version to 0.5.6
- Remove crashing when API calls the API fails to initialize (found in TypeError: 'NoneType' object is not iterable errors #136)
- Add battery discharge and charge buttons (15/30 mins and 1 hour) to all batteries but the Storion-S5 *pending AlphaESS confirmation if it works or not 
- Add reset charge/discharge battery. to set all configs to 00:00 (aka resetting them)
- discharge and charge buttons can each only be pressed once every 10 mins (OpenAPI limitation) 
- Supports using via automations (good for people using the Amber integration) 
- Due to the limitations of the API, the discharge and charge config will round up to the nearest 15 min (eg at 12:02 you press the 15 min discharge config. it wont go live until 12:15, and it wont finish until 12:30)
- Show the data being provided from getDisChargeConfigInfo and getChargeConfigInfo
- Add charging range for the battery
image
image

### CODE REVIEW

**Comment by CharlesGillanders** [comment]
@Poshy163 - you've been busy on this for quite a while, let me know when you want it merged with the repo.

**Comment by Poshy163** [comment]
@CharlesGillanders, you mind giving me write access to the repo incase this goes pear shape for the Storion-S5 invertors (and possibly more) and i need to push an update ASAP after this is released? 

i have a feeling it should work, and from what ive talked with elevenfan in the slack channel about what parameters it supports, he said it "should" and when i asked for proof, he said he would "search the database myself" and i am yet to hear back about it (not a surprise) 

image

**Comment by Poshy163** [comment]
> if that is not sufficient let me know and I'll do whatever else is needed.

Seems to be working, i can draft/make a new release but still cant approve my own PR (seems i can push directly to the repo based on [this graph](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization)

Might be worth moving it the role to maintainer for now?, or could just yolo it and deal with it when something inevitably goes wrong with a change this size 🤣

**Comment by CharlesGillanders** [comment]
> Might be worth moving it the role to maintainer for now?, or could just yolo it and deal with it when something inevitably goes wrong with a change this size 🤣

So a little bit of additional reading on my part suggests that when using a personal account there is very limited ability to grant additional roles or permissions.  I'd need to move this repo to an organization to be able to do that.  Worth considering doing but possibly more headache than is needed immediately...

**Comment by Poshy163** [comment]
Ah yeah, that's no stress. Maybe write perms are enough for just pushing any major blocking fixes out to everyone

**Comment by Poshy163** [comment]
@CharlesGillanders should be good to go now 👍🏻

**Review by CharlesGillanders — APPROVED** [review]

**Comment by CharlesGillanders** [comment]
> @CharlesGillanders should be good to go now 👍🏻 i can release it if you wanna merge it 

All yours.

**Comment by matt-oneill** [comment]
How have you added support for Force battery discharge, I don't think alpha essential have added this to the open api?
Good idea adding the buttons for quick charge and the diagnostic values.

Have you also had issues with open api not setting the charge settings? mine hasn't worked since their last 'upgrade'

**Comment by Poshy163** [comment]
Force battery discharge just works by setting the discharge time to the nearest quarter of an hour.

As for if it's working, I'm having no issues (in AUS + Smile5) so that's what I was doing the tests off of

**Pull request merged**
