### PR TITLE
Support State of Charge for Storion-S5

### PR DESCRIPTION
**Pull request by Poshy163**
# Breaking
Removes `state of charge` from non Storion-S5 inverters, instead opting to use only `Instantaneous Battery SOC`
# Changed 
- Make `state of charge`  the associated method for Storion-S5 inverters SOC %
- Bump API version to 0.0.11
- Update version for release v0.5.4

### CODE REVIEW

**Comment by homeconnexde** [comment]
Thank you. Then I'm waiting for the API change.

**Comment by CharlesGillanders** [comment]
OpenAPI 0.0.11 is published to PyPi.

**Comment by Poshy163** [comment]
Cool, @homeconnexde give it a crack and see how it goes

**Comment by homeconnexde** [comment]
Hmm, i now got 17 entities but no SOC

image

**Comment by homeconnexde** [comment]
Here is a screenshot with the full entity names

image

**Comment by Poshy163** [comment]
Interesting, no `State of Charge` sensor, did you copy the sensorlist.py file?

**Comment by homeconnexde** [comment]
I did a reinstallation and now there is a SOC but it is 0% while it is 100% actually.

image

**Comment by Poshy163** [comment]
Cheers for that @homeconnexde, can you add this line in at line 94 and let me know what the logs say?
`_LOGGER.info(f"CBAT DATA IS: {first_entry}")` 
should look like this then:
image

**Comment by homeconnexde** [comment]
Worked:

image

**Comment by homeconnexde** [comment]
Great job :-) Thank you very much.

**Comment by Poshy163** [comment]
Heh dope, ill do some clean and merge it. thanks so much for your help!

**Comment by homeconnexde** [comment]
It is still working. now it says Version 0.5.4

**Comment by Poshy163** [comment]
Nice, cheers for that!

**Comment by Poshy163** [comment]
@CharlesGillanders this pull bumps the API version to 0.0.11 and also bumps the version in the manifest file to 0.5.4

**Review by CharlesGillanders — APPROVED** [review]

**Pull request merged**
