### PR TITLE
Storion-S5 System fix and Improvements

### LINKED ISSUE #111: TypeError: unsupported operand type
How can I solve it?
I saw differents people with the same issue, but I didn't understand the solution.
Here is the log:
Questo errore ha avuto origine da un'integrazione personalizzata.

Registratore: custom_components.alphaess
Fonte: helpers/update_coordinator.py:315
Integrazione: Alpha ESS (documentazione, problemi)
Prima occorrenza: 00:00:22 (428 occorrenze)
Ultima registrazione: 07:37:43

Unexpected error fetching alphaess data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alphaess/coordinator.py", line 56, in _async_update_data
    inverterdata.update({"Solar to Load": _pv - _feedin})
                                          ~~~~^~~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

### PR DESCRIPTION
**Pull request by Poshy163**
TODO: 

- Add additional data points provided by the API.
- Check if any data points from the API are blank or a whitespace, if so. default to 0 (should fix #111 and #112)
- If multiple inverters exists, throttle the subsequent inverters calls to reduce the chance of a 6053 max requests error 
....

### CODE REVIEW

**Comment by Poshy163** [comment]
Throttling was done in response to [this](https://github.com/alphaess-developer/alphacloud_open_api/issues/56). which only allows a certain amount of calls every 10s. 

For this to work, needs this [pull](https://github.com/CharlesGillanders/alphaess-openAPI/pull/13) in the open-API

*currently, it spits out an error once until the amount of inverters can be read, then subsequent calls are fine

**Comment by CharlesGillanders** [comment]
I merged your pull request in the Open API library - if you bump the library version to 0.0.10 now in the home assistant integration that should have the optional delay function working.

**Comment by Poshy163** [comment]
Cheers, ill bump the version in this PR

**Comment by Poshy163** [comment]
With the fix for the Storion-S5 systems, essentially what the best way of approaching it is having 2 lists of sensors, a "limited" and "full" list of sensors, where the Storion-S5 uses only the values it can, then within the coordinator, if we just check each value to check if its null, and if so, convert it to 0 (to stop it from chocking up). converting to 0 shouldn't make a difference as we are not displaying any of those values, or the values it is used to calculate with

**Comment by Poshy163** [comment]
Maybe run this as a beta @CharlesGillanders to make sure i weed out any of the possible outliers 🥲

**Review by CharlesGillanders — APPROVED** [review]

**Comment by imascarenhas** [comment]
Nice work on the changes, just installed the beta and noticed a minor issue. The new Total Income sensor seems to be hardcoded to use "$" for the currancy rather than take it from the value set in Home Assistant.

**Comment by homeconnexde** [comment]
Now I am not able to install de integration again. I got: {"message":"Invalid handler specified"}

**Comment by Poshy163** [comment]
@homeconnexde can you make a separate github issue for it

**Comment by homeconnexde** [comment]
Ok I managed to do the installation without the invalid handler failure. I entered Api and App Key. Ist says Configuration success after entering AppId and App Secret. And then it sticks with initializing... and the initializing failure, trying again...

**Comment by homeconnexde** [comment]
While in HACS it says 0.50beta in upper left corner, the Home Assitant Settings integration still says 0.49. But I deleted the alphaess folder in custom components before reinstalling via HACS

**Comment by Poshy163** [comment]
Did you reboot after installing the beta? 

Try deleting the AlphaESS folder in custom components, and then reinstall the beta, restart your home assistant instance. Then try to add your appID/Secret

**Comment by homeconnexde** [comment]
Yes, is it the way how I could fix the handle exception issue.

I deleted the alpha folder in custom components. 

Full reboot of HA

Then re-download via HACS. 

Full reboot of HA

Add alphaess integration via HACS add integration link

**Comment by AuTHeNTiiiX** [comment]
Integration still nit intialition with Version 5.2

I getting this error

Unexpected error fetching alphaess data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alphaess/coordinator.py", line 90, in _async_update_data
    inverterdata["Instantaneous PPV1"] = await process_value(_pvpowerdetails.get("ppv1"))
                                                             ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Poshy163** [comment]
@AuTHeNTiiiX cheers for that, can you make an issue. and include what the logs say, there should be a value that has includes your serial number, and model 
`_LOGGER.info(f"Serial: {serial}, Model: {model}")` 
(where {serial} is the serial number of the inverter, you can blank this out, and {model} is the model, which i need)  

you should beable to find it quickly by opening the logs, Settings > System > Logs > Load all logs. then doing control + F and searching for model . should be a bit like this
image

**Pull request merged**
