### PR TITLE
Small QOL improvements 

### PR DESCRIPTION
**Pull request by Poshy163**
- Move EMS Status to Diagnostic view
- Add support for custom icons (currently for self-consumption, self-sufficiency and total income)
- Add maximum battery capacity sensor
- Add installed and current capacity diagnostic sensor

### CODE REVIEW

**Review by CharlesGillanders — APPROVED** [review]

**Comment by CharlesGillanders** [comment]
Hi @Poshy163, you'll note that having merged the previous pull request there is now a merge conflict in this one.  Let me know if you are able to modify the pull request to eliminate the conflict?

**Comment by Poshy163** [comment]
That should of fixed it?

**Review by CharlesGillanders — APPROVED** [review]

**Comment by CharlesGillanders** [comment]
> That should of fixed it?

It looks to me that the default value for minv and emsStatus are not being passed into process_value, either that or I'm just reading the merge conflict incorrectly (also very possible).  

This is the current code that's in main branch:

inverterdata["Model"] = await process_value(invertor.get("minv"), 0)
inverterdata["EMS Status"] = await process_value(invertor.get("emsStatus"), 0)

The pull request seems to have:

inverterdata["Model"] = await process_value(invertor.get("minv"))
inverterdata["EMS Status"] = await process_value(invertor.get("emsStatus"))

**Comment by CharlesGillanders** [comment]
Ignore me!  I just saw that the process_value code was also updated to remove the need for the default.  I'll get this merged now.

**Comment by Poshy163** [comment]
haha, cheers man!

**Comment by CharlesGillanders** [comment]
Something has gotten broken somewhere, there are several of your changes (including the switch from default value to 0) that now appear to be missing from the pull request and the checks are failing due to indenting.  Is the easiest fix to cancel this PR and submit a new one?

**Pull request closed without merging**
